name: pull-request
on:
  pull_request:
    branches: [ "master" ]


jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission and test
        run: |
          chmod +x ./gradlew
          ./gradlew --info test
